name: CompoundCalculatorWorkflow

on:
  workflow_dispatch:
  
  push:
    branches:
    - 'master'
    
  pull_request:
    branches:
    - 'master'

jobs:
  TestProcess:
  
    if: github.ref_name != 'master'
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
      
    - name: Run tests
      run: dotnet test -c Release --verbosity normal
        
  PublishProcess:
  
    if: github.ref_name == 'master'
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
      
    - name: Build solution
      run: dotnet build -c Release --no-incremental
      
    - name: Produce nuget package
      run: dotnet pack -c Release -o .
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: CompoundCalculator_${{ github.sha }}
        path: CompoundCalculator.*.nupkg      
